# docker-compose.yaml
#api版本
version: "3"
services:
  mysql: #服务名称（不是容器名）
    container_name: mysql
    hostname: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    networks:
      - "c7nNetwork"

  app: #服务名称（不是容器名）
    container_name: app
    hostname: app
    image: app
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - "c7nNetwork"

networks:
  c7nNetwork:
    driver: bridge